version: '3'

services:
  database:
    restart: always
    image: postgres:latest
    ports:
      - "1000:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  backend:
    build: ./backend/
    ports:
      - "2000:8080"
    depends_on:
      - database

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
